name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Create env file
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env.production
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env.production
          echo "VITE_ALPHA_VANTAGE_API_KEY=${{ secrets.VITE_ALPHA_VANTAGE_API_KEY }}" >> .env.production

      - name: Verify env file
        run: |
          echo "Checking environment file..."
          if [ ! -f .env.production ]; then
            echo "Error: .env.production file not created"
            exit 1
          fi
          if ! grep -q VITE_SUPABASE_URL .env.production; then
            echo "Error: VITE_SUPABASE_URL not in .env.production"
            exit 1
          fi
          if ! grep -q VITE_SUPABASE_ANON_KEY .env.production; then
            echo "Error: VITE_SUPABASE_ANON_KEY not in .env.production"
            exit 1
          fi
          if ! grep -q VITE_ALPHA_VANTAGE_API_KEY .env.production; then
            echo "Error: VITE_ALPHA_VANTAGE_API_KEY not in .env.production"
            exit 1
          fi
          echo "Environment file verified successfully"

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
